<?php

namespace OLOG\Auth;

class Permission
{
    const PERMISSION_PHPAUTH_MANAGE_USERS = "PERMISSION_PHPAUTH_MANAGE_USERS";
    const PERMISSION_PHPAUTH_MANAGE_OPERATORS = "PERMISSION_PHPAUTH_MANAGE_OPERATORS";

}