<?php
declare(strict_types=1);

/**
 * @author Oleg Loginov <olognv@gmail.com>
 */

namespace OLOG\Auth;

class Permissions
{
    const PERMISSION_PHPAUTH_MANAGE_USERS = 'PERMISSION_PHPAUTH_MANAGE_USERS';
    const PERMISSION_PHPAUTH_MANAGE_USERS_PERMISSIONS = 'PERMISSION_PHPAUTH_MANAGE_USERS_PERMISSIONS';
    const PERMISSION_PHPAUTH_MANAGE_GROUPS = 'PERMISSION_PHPAUTH_MANAGE_GROUPS';
}
